# config
title: Blog of Wonder
description: Not all those who wander are lost
url: "https://jarkanni.com"
baseurl: ""

# build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# pagination
paginate: 5
paginate_path: "/page:num/"
