# config
title: The Peachy Observer
description: Even small steps lead to many miles
url: "https://blog.peacharonies.com"
baseurl: ""

# social links
minima:
  social_links:
    github: jarkanni

# build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# pagination
paginate: 5
paginate_path: "/page:num/"
