# config
title: The Peachy Observer
description: Even small steps lead to many miles
url: "https://blog.peacharonies.com"
baseurl: ""

# custom navigation
navigation:
  - title: Home
    url: /
  - title: GitHub
    url: https://github.com/jarkanni

# build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# pagination
paginate: 5
paginate_path: "/page:num/"
