# config
title: The Peachy Observer
description: Even small steps lead to many miles
url: "https://blog.peacharonies.com"
baseurl: ""

# build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# pagination
paginate: 5
paginate_path: "/page:num/"

# social links
github_username: jarkanni
